netid: "fak23"
password: "1234jkl;"
gmail: "faiaz.a.khan@gmail.com"
sendgrid: "yalego"
sendgrid_password: "yalego"
aws_access_key_id: AKIAIGVNEJUWP6KDGC6A
aws_secret_access_key: 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
gmaps_key: AIzaSyDxC7qcloU94l5dvOEdAoQTZ7AijIX65gw
facebook_app_id: "444785732265505"
facebook_app_secret: b27564eae1fab0c4841cbe049db7e9e3
