# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: gandalf_development
  pool: 5
  username: gandalf
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gandalf_test
  pool: 5
  username: gandalf
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d5hs65te5mm38b
  username: zmvlxykujbhufz
  password: PD9K9d3nl0_nX0ay0YPhBCcuKB
  host: ec2-23-21-161-255.compute-1.amazonaws.com
  port: 5432